[package]
name = "prism"
version = "0.1.0"
authors = ["zhengshaodong <ngxcorpio@gmail.com>"]
license = "MIT"
description = "Prism"
repository = "https://github.com/asura-pro/prism"
documentation = "https://docs.rs/prism"
keywords = ["prism"]

[dependencies]
